import {
  internalMutation,
  internalQuery,
  type MutationCtx,
} from "../_generated/server";
import { v } from "convex/values";
import { type Id } from "../_generated/dataModel";
import { contactEntryKindValidator } from "../contacts/schema";
import { validateValue as validateContactValue } from "../contacts/mutations";
import {
  buildReferencedStorageSet,
  collectReferencedFromCandidates,
} from "../content/storageRegistry";

const TEST_EMAIL_SUFFIX = "@mirror.test";
const MAX_TEST_CLEANUP_IDS = 100;
const DEFAULT_STORAGE_CLEANUP_LIMIT = 200;
const TEST_COVER_ARTICLE_SLUG_PATTERN =
  /^(?:artifact-video-shot|cover-video|inline-cover-video)(?:-|$)/;

type StorageCleanupResult = {
  deletedStorage: number;
  deletedOwnership: number;
  preservedReferenced: number;
};

function assertTestEmail(email: string): void {
  if (!email.endsWith(TEST_EMAIL_SUFFIX)) {
    throw new Error(
      `Test helpers only accept emails ending in ${TEST_EMAIL_SUFFIX}`,
    );
  }
}

function uniqueStorageIds(
  ids: Array<Id<"_storage"> | undefined>,
): Id<"_storage">[] {
  const out: Id<"_storage">[] = [];
  const seen = new Set<string>();
  for (const id of ids) {
    if (id === undefined || seen.has(id)) continue;
    seen.add(id);
    out.push(id);
  }
  return out;
}

function clampCleanupLimit(value: number | undefined): number {
  if (value === undefined || !Number.isFinite(value)) {
    return DEFAULT_STORAGE_CLEANUP_LIMIT;
  }
  return Math.max(1, Math.min(Math.floor(value), 500));
}

function storageSizeBytes(storage: { size?: number } | null): number {
  return typeof storage?.size === "number" ? storage.size : 0;
}

async function deleteCoverOwnership(
  ctx: MutationCtx,
  storageId: Id<"_storage">,
): Promise<number> {
  const row = await ctx.db
    .query("coverImageOwnership")
    .withIndex("by_storageId", (q) => q.eq("storageId", storageId))
    .unique();
  if (!row) return 0;
  await ctx.db.delete(row._id);
  return 1;
}

async function cleanupUnreferencedStorageIds(
  ctx: MutationCtx,
  ids: Id<"_storage">[],
): Promise<StorageCleanupResult> {
  const storageIds = uniqueStorageIds(ids);
  if (storageIds.length === 0) {
    return {
      deletedStorage: 0,
      deletedOwnership: 0,
      preservedReferenced: 0,
    };
  }

  const referenced = await collectReferencedFromCandidates(ctx, storageIds);
  let deletedStorage = 0;
  let deletedOwnership = 0;
  let preservedReferenced = 0;

  for (const storageId of storageIds) {
    if (referenced.has(storageId)) {
      preservedReferenced += 1;
      continue;
    }
    const storage = await ctx.db.system.get(storageId);
    if (storage !== null) {
      await ctx.storage.delete(storageId);
      deletedStorage += 1;
    }
    deletedOwnership += await deleteCoverOwnership(ctx, storageId);
  }

  return { deletedStorage, deletedOwnership, preservedReferenced };
}

/**
 * Stores a real OTP generated by Better Auth for a test email address.
 * Called from the emailOTP sendVerificationOTP callback when PLAYWRIGHT_TEST_SECRET is set.
 * The test-session route reads this value back via readTestOtp to complete the sign-in flow.
 *
 * WARNING: Only valid for emails ending in @mirror.test. Never expose as public API.
 */
export const storeTestOtp = internalMutation({
  args: {
    email: v.string(),
    otp: v.string(),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const existing = await ctx.db
      .query("testOtpStore")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    if (existing) {
      await ctx.db.patch(existing._id, {
        otp: args.otp,
        createdAt: Date.now(),
      });
    } else {
      await ctx.db.insert("testOtpStore", {
        email: args.email,
        otp: args.otp,
        createdAt: Date.now(),
      });
    }

    return null;
  },
});

/**
 * Reads the stored OTP for a test email address.
 * Called from the /test/read-otp HTTP action so the test-session route can complete sign-in.
 *
 * WARNING: Only valid for emails ending in @mirror.test. Never expose as public API.
 */
export const readTestOtp = internalQuery({
  args: {
    email: v.string(),
  },
  returns: v.union(v.string(), v.null()),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const record = await ctx.db
      .query("testOtpStore")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    return record?.otp ?? null;
  },
});

/**
 * Upserts the app-level users row for a test user.
 * Sets username, name, and onboardingComplete so tests can proceed past onboarding.
 *
 * WARNING: Only call from test infrastructure. Never expose as public API.
 */
export const ensureTestUser = internalMutation({
  args: {
    email: v.string(),
    username: v.string(),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const existing = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    // Refuse to claim a username already owned by a different (non-test) email.
    // Use `.collect()` rather than `.unique()` because dev/test environments can
    // accumulate duplicate rows with the same username across multiple test
    // emails (e.g. "test-user" shared by several @mirror.test accounts). The
    // original invariant we care about is "no NON-test user owns this username"
    // — duplicates among test users are harmless here.
    const usernameOwners = await ctx.db
      .query("users")
      .withIndex("by_username", (q) => q.eq("username", args.username))
      .collect();
    const blockingOwner = usernameOwners.find(
      (owner) =>
        owner.email !== args.email && !owner.email.endsWith(TEST_EMAIL_SUFFIX),
    );
    if (blockingOwner) {
      throw new Error(
        `Username ${args.username} is already owned by a non-test user`,
      );
    }

    if (existing) {
      await ctx.db.patch(existing._id, {
        username: args.username,
        name: "Test User",
        onboardingComplete: true,
      });
    } else {
      await ctx.db.insert("users", {
        authId: `test_${args.email}`,
        email: args.email,
        username: args.username,
        name: "Test User",
        onboardingComplete: true,
      });
    }

    return null;
  },
});

/**
 * Resets the app-level users row for a test user into the authed-but-not-onboarded
 * state: `username` unset, `name`/`bio` cleared, and `onboardingComplete` false.
 * Idempotent — if the row doesn't exist yet (Better Auth `onCreate` trigger will
 * create it with the same shape), this is a no-op.
 *
 * Used by the no-username Playwright fixture so a row that was previously
 * onboarded (by a prior run or manual repro) is forced back to the
 * no-username state every run, instead of silently passing through
 * auth-routing tests as a fully-onboarded user.
 *
 * WARNING: Only call from test infrastructure. Never expose as public API.
 */
export const resetTestUser = internalMutation({
  args: {
    email: v.string(),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const existing = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();
    if (!existing) return null;

    await ctx.db.patch(existing._id, {
      username: undefined,
      name: undefined,
      tagline: undefined,
      onboardingComplete: false,
    });
    return null;
  },
});

const DRAFT_FIXTURE_SLUG = "test-fixture-draft";
const PUBLISHED_FIXTURE_SLUG = "test-fixture-published";

/**
 * Idempotently creates one draft post and one published post owned by the test user.
 * Uses fixed slugs so repeated calls are safe (upsert by slug).
 * Returns the slugs so e2e tests can navigate directly to the fixture posts.
 *
 * WARNING: Only call from test infrastructure. Never expose as public API.
 */
export const ensureTestPostFixtures = internalMutation({
  args: {
    email: v.string(),
  },
  returns: v.object({
    draftSlug: v.string(),
    publishedSlug: v.string(),
  }),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const user = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    if (!user) {
      throw new Error(
        `Test user with email ${args.email} not found. Call ensureTestUser first.`,
      );
    }

    const userId = user._id;
    const now = Date.now();

    // Upsert draft post
    const existingDraft = await ctx.db
      .query("posts")
      .withIndex("by_userId_and_slug", (q) =>
        q.eq("userId", userId).eq("slug", DRAFT_FIXTURE_SLUG),
      )
      .unique();

    if (existingDraft) {
      // Always reset to an empty body + cleared cover so e2e specs that
      // paste/save inline images do not leak state into the next run.
      // Mirrors the article fixture's behavior.
      await ctx.db.patch(existingDraft._id, {
        status: "draft",
        title: "Test Draft Post",
        publishedAt: undefined,
        body: { type: "doc", content: [{ type: "paragraph" }] },
        coverImageStorageId: undefined,
      });
    } else {
      await ctx.db.insert("posts", {
        userId,
        slug: DRAFT_FIXTURE_SLUG,
        title: "Test Draft Post",
        body: { type: "doc", content: [{ type: "paragraph" }] },
        category: "test",
        createdAt: now,
        status: "draft",
      });
    }

    // Upsert published post
    const existingPublished = await ctx.db
      .query("posts")
      .withIndex("by_userId_and_slug", (q) =>
        q.eq("userId", userId).eq("slug", PUBLISHED_FIXTURE_SLUG),
      )
      .unique();

    if (existingPublished) {
      await ctx.db.patch(existingPublished._id, {
        status: "published",
        title: "Test Published Post",
        publishedAt: existingPublished.publishedAt ?? now,
        body: existingPublished.body ?? {
          type: "doc",
          content: [{ type: "paragraph" }],
        },
      });
    } else {
      await ctx.db.insert("posts", {
        userId,
        slug: PUBLISHED_FIXTURE_SLUG,
        title: "Test Published Post",
        body: { type: "doc", content: [{ type: "paragraph" }] },
        category: "test",
        createdAt: now,
        publishedAt: now,
        status: "published",
      });
    }

    return {
      draftSlug: DRAFT_FIXTURE_SLUG,
      publishedSlug: PUBLISHED_FIXTURE_SLUG,
    };
  },
});

const ARTICLE_DRAFT_FIXTURE_SLUG = "test-article-fixture-draft";
const ARTICLE_PUBLISHED_FIXTURE_SLUG = "test-article-fixture-published";
const ARTICLE_RELEVANT_FIXTURE_SLUG = "greyboard-software-with-less-input";
const ARTICLE_RELEVANT_FIXTURE_TITLE = "Software with Less Input";
// Per-spec key shape: `inline-<key>-fixture-draft`. The key is constrained so
// the resulting slug always passes the canonical slug pattern
// (`^[a-z0-9]+(?:-[a-z0-9]+)*$`) — see packages/convex/convex/content/slug.ts.
const FIXTURE_KEY_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/**
 * Idempotently creates one draft article and one published article owned by
 * the test user. Mirrors `ensureTestPostFixtures` so e2e specs that exercise
 * the article edit page (`[username]/articles/[slug]/edit`) can land on a
 * fixture article without going through the article-create UI flow (which
 * does not exist as a self-serve UI in Mirror today). Returns the slugs so
 * tests can navigate directly.
 *
 * `key` (optional): scopes the draft slug to a per-spec key so parallel
 * Playwright workers running sibling specs can't pollute each other's body
 * assertions. When provided, the draft slug is `inline-<key>-fixture-draft`;
 * when absent, the legacy `test-article-fixture-draft` slug is used so any
 * non-inline-image consumers of this fixture remain unaffected. The
 * published slug is shared (read-only across specs).
 *
 * WARNING: Only call from test infrastructure. Never expose as public API.
 */
export const ensureTestArticleFixtures = internalMutation({
  args: {
    email: v.string(),
    key: v.optional(v.string()),
    relevantArticle: v.optional(v.boolean()),
  },
  returns: v.object({
    draftSlug: v.string(),
    publishedSlug: v.string(),
    relevantSlug: v.optional(v.string()),
    relevantTitle: v.optional(v.string()),
    relevantArticleId: v.optional(v.id("articles")),
  }),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    if (args.key !== undefined && !FIXTURE_KEY_PATTERN.test(args.key)) {
      throw new Error(
        `ensureTestArticleFixtures: key must match ${FIXTURE_KEY_PATTERN}; got "${args.key}"`,
      );
    }

    const draftSlug = args.key
      ? `inline-${args.key}-fixture-draft`
      : ARTICLE_DRAFT_FIXTURE_SLUG;

    const user = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    if (!user) {
      throw new Error(
        `Test user with email ${args.email} not found. Call ensureTestUser first.`,
      );
    }

    const userId = user._id;
    const now = Date.now();
    const emptyBody = { type: "doc", content: [{ type: "paragraph" }] };

    // Upsert draft article
    const existingDraft = await ctx.db
      .query("articles")
      .withIndex("by_userId_and_slug", (q) =>
        q.eq("userId", userId).eq("slug", draftSlug),
      )
      .unique();

    if (existingDraft) {
      // Always reset the body so concurrent / sequential e2e tests start from
      // a deterministic empty draft. Inline-image specs paste images into
      // the draft and save, which would otherwise leak into the next run.
      // Cover blobs (image + PLAN_010 video + poster) are similarly cleared,
      // then reclaimed if no other row references them. This keeps repeated
      // local e2e runs from turning fixture resets into storage leaks.
      const previousCoverStorageIds = uniqueStorageIds([
        existingDraft.coverImageStorageId,
        existingDraft.coverVideoStorageId,
        existingDraft.coverVideoPosterStorageId,
      ]);
      await ctx.db.patch(existingDraft._id, {
        status: "draft",
        title: "Test Draft Article",
        publishedAt: undefined,
        body: emptyBody,
        coverImageStorageId: undefined,
        coverImageThumbhash: undefined,
        coverVideoStorageId: undefined,
        coverVideoPosterStorageId: undefined,
      });
      await cleanupUnreferencedStorageIds(ctx, previousCoverStorageIds);
    } else {
      await ctx.db.insert("articles", {
        userId,
        slug: draftSlug,
        title: "Test Draft Article",
        body: emptyBody,
        category: "test",
        createdAt: now,
        status: "draft",
      });
    }

    // Upsert published article
    const existingPublished = await ctx.db
      .query("articles")
      .withIndex("by_userId_and_slug", (q) =>
        q.eq("userId", userId).eq("slug", ARTICLE_PUBLISHED_FIXTURE_SLUG),
      )
      .unique();

    if (existingPublished) {
      await ctx.db.patch(existingPublished._id, {
        status: "published",
        title: "Test Published Article",
        publishedAt: existingPublished.publishedAt ?? now,
        body: existingPublished.body ?? emptyBody,
      });
    } else {
      await ctx.db.insert("articles", {
        userId,
        slug: ARTICLE_PUBLISHED_FIXTURE_SLUG,
        title: "Test Published Article",
        body: emptyBody,
        category: "test",
        createdAt: now,
        publishedAt: now,
        status: "published",
      });
    }

    let relevantArticleId: Id<"articles"> | undefined;
    if (args.relevantArticle === true) {
      const relevantBody = {
        type: "doc",
        content: [
          {
            type: "paragraph",
            content: [
              {
                type: "text",
                text: "Greyboard AI is a project about making software with less input, where agents handle configuration and complexity so people can think, write, and express ideas with less friction.",
              },
            ],
          },
          {
            type: "paragraph",
            content: [
              {
                type: "text",
                text: "The article explains why many tools add cognitive load while trying to reduce it, and why Greyboard explores interfaces that help people own their thinking.",
              },
            ],
          },
        ],
      };

      const existingRelevant = await ctx.db
        .query("articles")
        .withIndex("by_userId_and_slug", (q) =>
          q.eq("userId", userId).eq("slug", ARTICLE_RELEVANT_FIXTURE_SLUG),
        )
        .unique();

      if (existingRelevant) {
        relevantArticleId = existingRelevant._id;
        await ctx.db.patch(existingRelevant._id, {
          status: "published",
          title: ARTICLE_RELEVANT_FIXTURE_TITLE,
          category: "test",
          publishedAt: existingRelevant.publishedAt ?? now,
          body: relevantBody,
        });
      } else {
        relevantArticleId = await ctx.db.insert("articles", {
          userId,
          slug: ARTICLE_RELEVANT_FIXTURE_SLUG,
          title: ARTICLE_RELEVANT_FIXTURE_TITLE,
          body: relevantBody,
          category: "test",
          createdAt: now,
          publishedAt: now,
          status: "published",
        });
      }
    }

    return {
      draftSlug,
      publishedSlug: ARTICLE_PUBLISHED_FIXTURE_SLUG,
      ...(args.relevantArticle === true
        ? {
            relevantSlug: ARTICLE_RELEVANT_FIXTURE_SLUG,
            relevantTitle: ARTICLE_RELEVANT_FIXTURE_TITLE,
            relevantArticleId,
          }
        : {}),
    };
  },
});

export const cleanupTestCoverStorageIds = internalMutation({
  args: {
    storageIds: v.array(v.id("_storage")),
  },
  returns: v.object({
    deletedStorage: v.number(),
    deletedOwnership: v.number(),
    preservedReferenced: v.number(),
  }),
  handler: async (ctx, args) => {
    if (args.storageIds.length > MAX_TEST_CLEANUP_IDS) {
      throw new Error(
        `cleanupTestCoverStorageIds accepts at most ${MAX_TEST_CLEANUP_IDS} ids`,
      );
    }

    return await cleanupUnreferencedStorageIds(ctx, args.storageIds);
  },
});

export const cleanupTestArticleCoverMedia = internalMutation({
  args: {
    email: v.string(),
    slugs: v.array(v.string()),
  },
  returns: v.object({
    patchedArticles: v.number(),
    candidateStorageIds: v.number(),
    deletedStorage: v.number(),
    deletedOwnership: v.number(),
    preservedReferenced: v.number(),
  }),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);
    if (args.slugs.length > MAX_TEST_CLEANUP_IDS) {
      throw new Error(
        `cleanupTestArticleCoverMedia accepts at most ${MAX_TEST_CLEANUP_IDS} slugs`,
      );
    }

    const user = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();
    if (!user) {
      return {
        patchedArticles: 0,
        candidateStorageIds: 0,
        deletedStorage: 0,
        deletedOwnership: 0,
        preservedReferenced: 0,
      };
    }

    let patchedArticles = 0;
    const candidates: Id<"_storage">[] = [];
    for (const slug of new Set(args.slugs)) {
      const article = await ctx.db
        .query("articles")
        .withIndex("by_userId_and_slug", (q) =>
          q.eq("userId", user._id).eq("slug", slug),
        )
        .unique();
      if (!article) continue;

      const storageIds = uniqueStorageIds([
        article.coverImageStorageId,
        article.coverVideoStorageId,
        article.coverVideoPosterStorageId,
      ]);
      if (storageIds.length === 0) continue;

      candidates.push(...storageIds);
      await ctx.db.patch(article._id, {
        coverImageStorageId: undefined,
        coverImageThumbhash: undefined,
        coverVideoStorageId: undefined,
        coverVideoPosterStorageId: undefined,
      });
      patchedArticles += 1;
    }

    const cleanup = await cleanupUnreferencedStorageIds(ctx, candidates);
    return {
      patchedArticles,
      candidateStorageIds: uniqueStorageIds(candidates).length,
      ...cleanup,
    };
  },
});

export const cleanupTestStorage = internalMutation({
  args: {
    email: v.string(),
    olderThanMs: v.number(),
    dryRun: v.boolean(),
    includeTestArticleCoverMedia: v.boolean(),
    maxStorageRows: v.optional(v.number()),
    maxArticles: v.optional(v.number()),
  },
  returns: v.object({
    dryRun: v.boolean(),
    storageScanned: v.number(),
    unreferencedStorageIds: v.number(),
    unreferencedBytes: v.number(),
    staleTestArticleCoverStorageIds: v.number(),
    staleTestArticleCoverBytes: v.number(),
    patchedTestArticles: v.number(),
    deletedStorage: v.number(),
    deletedOwnership: v.number(),
    preservedReferenced: v.number(),
  }),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);
    if (!Number.isFinite(args.olderThanMs) || args.olderThanMs < 0) {
      throw new Error("olderThanMs must be a non-negative finite number");
    }

    const cutoff = Date.now() - args.olderThanMs;
    const storageLimit = clampCleanupLimit(args.maxStorageRows);
    const storagePage = await ctx.db.system
      .query("_storage")
      .withIndex("by_creation_time", (q) => q.lt("_creationTime", cutoff))
      .take(storageLimit);
    const referenced = await buildReferencedStorageSet(ctx);

    const unreferencedIds: Id<"_storage">[] = [];
    let unreferencedBytes = 0;
    for (const storage of storagePage) {
      if (referenced.has(storage._id)) continue;
      unreferencedIds.push(storage._id);
      unreferencedBytes += storageSizeBytes(storage);
    }

    let staleTestArticleCoverBytes = 0;
    let patchedTestArticles = 0;
    const staleTestArticleCoverIds: Id<"_storage">[] = [];

    if (args.includeTestArticleCoverMedia) {
      const user = await ctx.db
        .query("users")
        .withIndex("by_email", (q) => q.eq("email", args.email))
        .unique();

      if (user) {
        const articleLimit = clampCleanupLimit(args.maxArticles);
        const articles = await ctx.db
          .query("articles")
          .withIndex("by_userId", (q) => q.eq("userId", user._id))
          .take(articleLimit);

        for (const article of articles) {
          if (article.status !== "draft") continue;
          if (!TEST_COVER_ARTICLE_SLUG_PATTERN.test(article.slug)) continue;

          const fieldUpdates: {
            coverImageStorageId?: undefined;
            coverImageThumbhash?: undefined;
            coverVideoStorageId?: undefined;
            coverVideoPosterStorageId?: undefined;
          } = {};
          const coverFields = [
            {
              storageId: article.coverImageStorageId,
              field: "coverImageStorageId" as const,
            },
            {
              storageId: article.coverVideoStorageId,
              field: "coverVideoStorageId" as const,
            },
            {
              storageId: article.coverVideoPosterStorageId,
              field: "coverVideoPosterStorageId" as const,
            },
          ];

          for (const coverField of coverFields) {
            if (coverField.storageId === undefined) continue;
            const storage = await ctx.db.system.get(coverField.storageId);
            if (storage !== null && storage._creationTime >= cutoff) continue;

            staleTestArticleCoverIds.push(coverField.storageId);
            staleTestArticleCoverBytes += storageSizeBytes(storage);
            fieldUpdates[coverField.field] = undefined;
            if (coverField.field === "coverImageStorageId") {
              fieldUpdates.coverImageThumbhash = undefined;
            }
          }

          if (!args.dryRun && Object.keys(fieldUpdates).length > 0) {
            await ctx.db.patch(article._id, fieldUpdates);
            patchedTestArticles += 1;
          }
        }
      }
    }

    if (args.dryRun) {
      return {
        dryRun: true,
        storageScanned: storagePage.length,
        unreferencedStorageIds: uniqueStorageIds(unreferencedIds).length,
        unreferencedBytes,
        staleTestArticleCoverStorageIds: uniqueStorageIds(
          staleTestArticleCoverIds,
        ).length,
        staleTestArticleCoverBytes,
        patchedTestArticles: 0,
        deletedStorage: 0,
        deletedOwnership: 0,
        preservedReferenced: 0,
      };
    }

    const unreferencedCleanup = await cleanupUnreferencedStorageIds(
      ctx,
      unreferencedIds,
    );
    const staleMediaCleanup = await cleanupUnreferencedStorageIds(
      ctx,
      staleTestArticleCoverIds,
    );

    return {
      dryRun: false,
      storageScanned: storagePage.length,
      unreferencedStorageIds: uniqueStorageIds(unreferencedIds).length,
      unreferencedBytes,
      staleTestArticleCoverStorageIds: uniqueStorageIds(
        staleTestArticleCoverIds,
      ).length,
      staleTestArticleCoverBytes,
      patchedTestArticles,
      deletedStorage:
        unreferencedCleanup.deletedStorage + staleMediaCleanup.deletedStorage,
      deletedOwnership:
        unreferencedCleanup.deletedOwnership +
        staleMediaCleanup.deletedOwnership,
      preservedReferenced:
        unreferencedCleanup.preservedReferenced +
        staleMediaCleanup.preservedReferenced,
    };
  },
});

/**
 * Idempotently seeds a configurable set of bioEntries rows for a test user,
 * deleting any pre-existing rows for that user first so the canonical fixture
 * state is reset on every call. Used by Wave-4 Playwright specs in
 * `apps/mirror/e2e/bio/` to drive list rendering, ordering, and 50-cap tests
 * deterministically.
 *
 * The shape of `entries` mirrors the public `bioEntries` schema (kind, title,
 * startDate, endDate, description?, link?). The caller — not this helper —
 * is responsible for picking start/end month-anchored epoch ms.
 *
 * NOTE: This intentionally bypasses the `bio.mutations.create` soft-cap so
 * Playwright can seed exactly 51 entries to verify FR-10 (the public query
 * caps reads at 50). Producing 51+ rows via the public mutation would race
 * the soft-cap.
 *
 * NOTE: This does NOT schedule embedding generation. Bio fixture rows used
 * by FR-12/FR-13 (RAG context) require additional fixture infrastructure
 * (clone configuration + a deterministic embedding pipeline).
 *
 * WARNING: Only call from test infrastructure. Never expose as public API.
 */
export const ensureTestBioFixtures = internalMutation({
  args: {
    email: v.string(),
    entries: v.array(
      v.object({
        kind: v.union(v.literal("work"), v.literal("education")),
        title: v.string(),
        startDate: v.number(),
        endDate: v.union(v.number(), v.null()),
        description: v.optional(v.string()),
        link: v.optional(v.string()),
      }),
    ),
  },
  returns: v.object({
    userId: v.id("users"),
    insertedCount: v.number(),
  }),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const user = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    if (!user) {
      throw new Error(
        `Test user with email ${args.email} not found. Call ensureTestUser first.`,
      );
    }

    const userId = user._id;

    // Wipe existing bioEntries for this user so each call resets to the
    // canonical fixture state.
    const existing = await ctx.db
      .query("bioEntries")
      .withIndex("by_userId", (q) => q.eq("userId", userId))
      .collect();
    for (const row of existing) {
      await ctx.db.delete(row._id);
    }

    for (const entry of args.entries) {
      await ctx.db.insert("bioEntries", {
        userId,
        kind: entry.kind,
        title: entry.title,
        startDate: entry.startDate,
        endDate: entry.endDate,
        description: entry.description,
        link: entry.link,
      });
    }

    return {
      userId,
      insertedCount: args.entries.length,
    };
  },
});

/**
 * Replaces the test user's contactEntries with `args.entries`. Mirrors
 * `ensureTestBioFixtures` — wipes existing rows for this user, then
 * re-inserts the supplied list. Used by Playwright e2e tests under
 * `apps/mirror/e2e/contact/*`.
 *
 * WARNING: Only call from test infrastructure. Never expose as public API.
 */
export const ensureTestContactFixtures = internalMutation({
  args: {
    email: v.string(),
    entries: v.array(
      v.object({
        kind: contactEntryKindValidator,
        value: v.string(),
      }),
    ),
  },
  returns: v.object({
    userId: v.id("users"),
    insertedCount: v.number(),
  }),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const user = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    if (!user) {
      throw new Error(
        `Test user with email ${args.email} not found. Call ensureTestUser first.`,
      );
    }

    const userId = user._id;

    const existing = await ctx.db
      .query("contactEntries")
      .withIndex("by_userId", (q) => q.eq("userId", userId))
      .collect();
    for (const row of existing) {
      await ctx.db.delete(row._id);
    }

    for (const entry of args.entries) {
      // Run fixtures through the same trust-boundary validator the public
      // create mutation uses so a test-mode actor cannot plant arbitrary
      // strings (e.g. prompt-injection payloads) that would flow through
      // the embedding pipeline into the RAG store.
      validateContactValue(entry.kind, entry.value);
      await ctx.db.insert("contactEntries", {
        userId,
        kind: entry.kind,
        value: entry.value.trim(),
      });
    }

    return {
      userId,
      insertedCount: args.entries.length,
    };
  },
});

