import { internalMutation, internalQuery } from "../_generated/server";
import { v } from "convex/values";

const TEST_EMAIL_SUFFIX = "@mirror.test";

function assertTestEmail(email: string): void {
  if (!email.endsWith(TEST_EMAIL_SUFFIX)) {
    throw new Error(
      `Test helpers only accept emails ending in ${TEST_EMAIL_SUFFIX}`,
    );
  }
}

/**
 * Stores a real OTP generated by Better Auth for a test email address.
 * Called from the emailOTP sendVerificationOTP callback when PLAYWRIGHT_TEST_SECRET is set.
 * The test-session route reads this value back via readTestOtp to complete the sign-in flow.
 *
 * WARNING: Only valid for emails ending in @mirror.test. Never expose as public API.
 */
export const storeTestOtp = internalMutation({
  args: {
    email: v.string(),
    otp: v.string(),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const existing = await ctx.db
      .query("testOtpStore")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    if (existing) {
      await ctx.db.patch(existing._id, {
        otp: args.otp,
        createdAt: Date.now(),
      });
    } else {
      await ctx.db.insert("testOtpStore", {
        email: args.email,
        otp: args.otp,
        createdAt: Date.now(),
      });
    }

    return null;
  },
});

/**
 * Reads the stored OTP for a test email address.
 * Called from the /test/read-otp HTTP action so the test-session route can complete sign-in.
 *
 * WARNING: Only valid for emails ending in @mirror.test. Never expose as public API.
 */
export const readTestOtp = internalQuery({
  args: {
    email: v.string(),
  },
  returns: v.union(v.string(), v.null()),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const record = await ctx.db
      .query("testOtpStore")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    return record?.otp ?? null;
  },
});

/**
 * Upserts the app-level users row for a test user.
 * Sets username, name, and onboardingComplete so tests can proceed past onboarding.
 *
 * WARNING: Only call from test infrastructure. Never expose as public API.
 */
export const ensureTestUser = internalMutation({
  args: {
    email: v.string(),
    username: v.string(),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const existing = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    // Refuse to claim a username already owned by a different (non-test) email.
    // Use `.collect()` rather than `.unique()` because dev/test environments can
    // accumulate duplicate rows with the same username across multiple test
    // emails (e.g. "test-user" shared by several @mirror.test accounts). The
    // original invariant we care about is "no NON-test user owns this username"
    // — duplicates among test users are harmless here.
    const usernameOwners = await ctx.db
      .query("users")
      .withIndex("by_username", (q) => q.eq("username", args.username))
      .collect();
    const blockingOwner = usernameOwners.find(
      (owner) =>
        owner.email !== args.email &&
        !owner.email.endsWith(TEST_EMAIL_SUFFIX),
    );
    if (blockingOwner) {
      throw new Error(
        `Username ${args.username} is already owned by a non-test user`,
      );
    }

    if (existing) {
      await ctx.db.patch(existing._id, {
        username: args.username,
        name: "Test User",
        onboardingComplete: true,
      });
    } else {
      await ctx.db.insert("users", {
        authId: `test_${args.email}`,
        email: args.email,
        username: args.username,
        name: "Test User",
        onboardingComplete: true,
      });
    }

    return null;
  },
});

/**
 * Resets the app-level users row for a test user into the authed-but-not-onboarded
 * state: `username` unset, `name`/`bio` cleared, and `onboardingComplete` false.
 * Idempotent — if the row doesn't exist yet (Better Auth `onCreate` trigger will
 * create it with the same shape), this is a no-op.
 *
 * Used by the no-username Playwright fixture so a row that was previously
 * onboarded (by a prior run or manual repro) is forced back to the
 * no-username state every run, instead of silently passing through
 * auth-routing tests as a fully-onboarded user.
 *
 * WARNING: Only call from test infrastructure. Never expose as public API.
 */
export const resetTestUser = internalMutation({
  args: {
    email: v.string(),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const existing = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();
    if (!existing) return null;

    await ctx.db.patch(existing._id, {
      username: undefined,
      name: undefined,
      bio: undefined,
      onboardingComplete: false,
    });
    return null;
  },
});

const DRAFT_FIXTURE_SLUG = "test-fixture-draft";
const PUBLISHED_FIXTURE_SLUG = "test-fixture-published";

/**
 * Idempotently creates one draft post and one published post owned by the test user.
 * Uses fixed slugs so repeated calls are safe (upsert by slug).
 * Returns the slugs so e2e tests can navigate directly to the fixture posts.
 *
 * WARNING: Only call from test infrastructure. Never expose as public API.
 */
export const ensureTestPostFixtures = internalMutation({
  args: {
    email: v.string(),
  },
  returns: v.object({
    draftSlug: v.string(),
    publishedSlug: v.string(),
  }),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const user = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    if (!user) {
      throw new Error(
        `Test user with email ${args.email} not found. Call ensureTestUser first.`,
      );
    }

    const userId = user._id;
    const now = Date.now();

    // Upsert draft post
    const existingDraft = await ctx.db
      .query("posts")
      .withIndex("by_userId_and_slug", (q) =>
        q.eq("userId", userId).eq("slug", DRAFT_FIXTURE_SLUG),
      )
      .unique();

    if (existingDraft) {
      await ctx.db.patch(existingDraft._id, {
        status: "draft",
        title: "Test Draft Post",
        publishedAt: undefined,
        body: existingDraft.body ?? { type: "doc", content: [{ type: "paragraph" }] },
      });
    } else {
      await ctx.db.insert("posts", {
        userId,
        slug: DRAFT_FIXTURE_SLUG,
        title: "Test Draft Post",
        body: { type: "doc", content: [{ type: "paragraph" }] },
        category: "test",
        createdAt: now,
        status: "draft",
      });
    }

    // Upsert published post
    const existingPublished = await ctx.db
      .query("posts")
      .withIndex("by_userId_and_slug", (q) =>
        q.eq("userId", userId).eq("slug", PUBLISHED_FIXTURE_SLUG),
      )
      .unique();

    if (existingPublished) {
      await ctx.db.patch(existingPublished._id, {
        status: "published",
        title: "Test Published Post",
        publishedAt: existingPublished.publishedAt ?? now,
        body: existingPublished.body ?? { type: "doc", content: [{ type: "paragraph" }] },
      });
    } else {
      await ctx.db.insert("posts", {
        userId,
        slug: PUBLISHED_FIXTURE_SLUG,
        title: "Test Published Post",
        body: { type: "doc", content: [{ type: "paragraph" }] },
        category: "test",
        createdAt: now,
        publishedAt: now,
        status: "published",
      });
    }

    return {
      draftSlug: DRAFT_FIXTURE_SLUG,
      publishedSlug: PUBLISHED_FIXTURE_SLUG,
    };
  },
});

const ARTICLE_DRAFT_FIXTURE_SLUG = "test-article-fixture-draft";
const ARTICLE_PUBLISHED_FIXTURE_SLUG = "test-article-fixture-published";

/**
 * Idempotently creates one draft article and one published article owned by
 * the test user. Mirrors `ensureTestPostFixtures` so e2e specs that exercise
 * the article edit page (`[username]/articles/[slug]/edit`) can land on a
 * fixture article without going through the article-create UI flow (which
 * does not exist as a self-serve UI in Mirror today). Returns the slugs so
 * tests can navigate directly.
 *
 * WARNING: Only call from test infrastructure. Never expose as public API.
 */
export const ensureTestArticleFixtures = internalMutation({
  args: {
    email: v.string(),
  },
  returns: v.object({
    draftSlug: v.string(),
    publishedSlug: v.string(),
  }),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const user = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    if (!user) {
      throw new Error(
        `Test user with email ${args.email} not found. Call ensureTestUser first.`,
      );
    }

    const userId = user._id;
    const now = Date.now();
    const emptyBody = { type: "doc", content: [{ type: "paragraph" }] };

    // Upsert draft article
    const existingDraft = await ctx.db
      .query("articles")
      .withIndex("by_userId_and_slug", (q) =>
        q.eq("userId", userId).eq("slug", ARTICLE_DRAFT_FIXTURE_SLUG),
      )
      .unique();

    if (existingDraft) {
      await ctx.db.patch(existingDraft._id, {
        status: "draft",
        title: "Test Draft Article",
        publishedAt: undefined,
        body: existingDraft.body ?? emptyBody,
      });
    } else {
      await ctx.db.insert("articles", {
        userId,
        slug: ARTICLE_DRAFT_FIXTURE_SLUG,
        title: "Test Draft Article",
        body: emptyBody,
        category: "test",
        createdAt: now,
        status: "draft",
      });
    }

    // Upsert published article
    const existingPublished = await ctx.db
      .query("articles")
      .withIndex("by_userId_and_slug", (q) =>
        q.eq("userId", userId).eq("slug", ARTICLE_PUBLISHED_FIXTURE_SLUG),
      )
      .unique();

    if (existingPublished) {
      await ctx.db.patch(existingPublished._id, {
        status: "published",
        title: "Test Published Article",
        publishedAt: existingPublished.publishedAt ?? now,
        body: existingPublished.body ?? emptyBody,
      });
    } else {
      await ctx.db.insert("articles", {
        userId,
        slug: ARTICLE_PUBLISHED_FIXTURE_SLUG,
        title: "Test Published Article",
        body: emptyBody,
        category: "test",
        createdAt: now,
        publishedAt: now,
        status: "published",
      });
    }

    return {
      draftSlug: ARTICLE_DRAFT_FIXTURE_SLUG,
      publishedSlug: ARTICLE_PUBLISHED_FIXTURE_SLUG,
    };
  },
});

/**
 * Idempotently seeds a configurable set of bioEntries rows for a test user,
 * deleting any pre-existing rows for that user first so the canonical fixture
 * state is reset on every call. Used by Wave-4 Playwright specs in
 * `apps/mirror/e2e/bio/` to drive list rendering, ordering, and 50-cap tests
 * deterministically.
 *
 * The shape of `entries` mirrors the public `bioEntries` schema (kind, title,
 * startDate, endDate, description?, link?). The caller — not this helper —
 * is responsible for picking start/end month-anchored epoch ms.
 *
 * NOTE: This intentionally bypasses the `bio.mutations.create` soft-cap so
 * Playwright can seed exactly 51 entries to verify FR-10 (the public query
 * caps reads at 50). Producing 51+ rows via the public mutation would race
 * the soft-cap.
 *
 * NOTE: This does NOT schedule embedding generation. Bio fixture rows used
 * by FR-12/FR-13 (RAG context) require additional fixture infrastructure
 * (clone configuration + a deterministic embedding pipeline).
 *
 * WARNING: Only call from test infrastructure. Never expose as public API.
 */
export const ensureTestBioFixtures = internalMutation({
  args: {
    email: v.string(),
    entries: v.array(
      v.object({
        kind: v.union(v.literal("work"), v.literal("education")),
        title: v.string(),
        startDate: v.number(),
        endDate: v.union(v.number(), v.null()),
        description: v.optional(v.string()),
        link: v.optional(v.string()),
      }),
    ),
  },
  returns: v.object({
    userId: v.id("users"),
    insertedCount: v.number(),
  }),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const user = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    if (!user) {
      throw new Error(
        `Test user with email ${args.email} not found. Call ensureTestUser first.`,
      );
    }

    const userId = user._id;

    // Wipe existing bioEntries for this user so each call resets to the
    // canonical fixture state.
    const existing = await ctx.db
      .query("bioEntries")
      .withIndex("by_userId", (q) => q.eq("userId", userId))
      .collect();
    for (const row of existing) {
      await ctx.db.delete(row._id);
    }

    for (const entry of args.entries) {
      await ctx.db.insert("bioEntries", {
        userId,
        kind: entry.kind,
        title: entry.title,
        startDate: entry.startDate,
        endDate: entry.endDate,
        description: entry.description,
        link: entry.link,
      });
    }

    return {
      userId,
      insertedCount: args.entries.length,
    };
  },
});

/**
 * Deletes testOtpStore rows older than TEST_OTP_TTL_MS. Scheduled from crons.ts
 * to keep the table from accumulating stale rows in dev/test environments.
 */
const TEST_OTP_TTL_MS = 10 * 60 * 1000; // 10 minutes

export const cleanupStaleTestOtps = internalMutation({
  args: {},
  returns: v.null(),
  handler: async (ctx) => {
    const cutoff = Date.now() - TEST_OTP_TTL_MS;
    const stale = await ctx.db
      .query("testOtpStore")
      .withIndex("by_createdAt", (q) => q.lt("createdAt", cutoff))
      .collect();
    for (const row of stale) {
      await ctx.db.delete(row._id);
    }
    return null;
  },
});
