import { internalMutation, internalQuery } from "../_generated/server";
import { v } from "convex/values";

const TEST_EMAIL_SUFFIX = "@mirror.test";

function assertTestEmail(email: string): void {
  if (!email.endsWith(TEST_EMAIL_SUFFIX)) {
    throw new Error(
      `Test helpers only accept emails ending in ${TEST_EMAIL_SUFFIX}`,
    );
  }
}

/**
 * Stores a real OTP generated by Better Auth for a test email address.
 * Called from the emailOTP sendVerificationOTP callback when PLAYWRIGHT_TEST_SECRET is set.
 * The test-session route reads this value back via readTestOtp to complete the sign-in flow.
 *
 * WARNING: Only valid for emails ending in @mirror.test. Never expose as public API.
 */
export const storeTestOtp = internalMutation({
  args: {
    email: v.string(),
    otp: v.string(),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const existing = await ctx.db
      .query("testOtpStore")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    if (existing) {
      await ctx.db.patch(existing._id, {
        otp: args.otp,
        createdAt: Date.now(),
      });
    } else {
      await ctx.db.insert("testOtpStore", {
        email: args.email,
        otp: args.otp,
        createdAt: Date.now(),
      });
    }

    return null;
  },
});

/**
 * Reads the stored OTP for a test email address.
 * Called from the /test/read-otp HTTP action so the test-session route can complete sign-in.
 *
 * WARNING: Only valid for emails ending in @mirror.test. Never expose as public API.
 */
export const readTestOtp = internalQuery({
  args: {
    email: v.string(),
  },
  returns: v.union(v.string(), v.null()),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const record = await ctx.db
      .query("testOtpStore")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    return record?.otp ?? null;
  },
});

/**
 * Upserts the app-level users row for a test user.
 * Sets username, name, and onboardingComplete so tests can proceed past onboarding.
 *
 * WARNING: Only call from test infrastructure. Never expose as public API.
 */
export const ensureTestUser = internalMutation({
  args: {
    email: v.string(),
    username: v.string(),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const existing = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    // Refuse to claim a username already owned by a different (non-test) email.
    const usernameOwner = await ctx.db
      .query("users")
      .withIndex("by_username", (q) => q.eq("username", args.username))
      .unique();
    if (
      usernameOwner &&
      usernameOwner.email !== args.email &&
      !usernameOwner.email.endsWith(TEST_EMAIL_SUFFIX)
    ) {
      throw new Error(
        `Username ${args.username} is already owned by a non-test user`,
      );
    }

    if (existing) {
      await ctx.db.patch(existing._id, {
        username: args.username,
        name: "Test User",
        onboardingComplete: true,
      });
    } else {
      await ctx.db.insert("users", {
        authId: `test_${args.email}`,
        email: args.email,
        username: args.username,
        name: "Test User",
        onboardingComplete: true,
      });
    }

    return null;
  },
});

const DRAFT_FIXTURE_SLUG = "test-fixture-draft";
const PUBLISHED_FIXTURE_SLUG = "test-fixture-published";

/**
 * Idempotently creates one draft post and one published post owned by the test user.
 * Uses fixed slugs so repeated calls are safe (upsert by slug).
 * Returns the slugs so e2e tests can navigate directly to the fixture posts.
 *
 * WARNING: Only call from test infrastructure. Never expose as public API.
 */
export const ensureTestPostFixtures = internalMutation({
  args: {
    email: v.string(),
  },
  returns: v.object({
    draftSlug: v.string(),
    publishedSlug: v.string(),
  }),
  handler: async (ctx, args) => {
    assertTestEmail(args.email);

    const user = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    if (!user) {
      throw new Error(
        `Test user with email ${args.email} not found. Call ensureTestUser first.`,
      );
    }

    const userId = user._id;
    const now = Date.now();

    // Upsert draft post
    const existingDraft = await ctx.db
      .query("posts")
      .withIndex("by_userId_and_slug", (q) =>
        q.eq("userId", userId).eq("slug", DRAFT_FIXTURE_SLUG),
      )
      .unique();

    if (existingDraft) {
      await ctx.db.patch(existingDraft._id, {
        status: "draft",
        title: "Test Draft Post",
        publishedAt: undefined,
        body: existingDraft.body ?? { type: "doc", content: [{ type: "paragraph" }] },
      });
    } else {
      await ctx.db.insert("posts", {
        userId,
        slug: DRAFT_FIXTURE_SLUG,
        title: "Test Draft Post",
        body: { type: "doc", content: [{ type: "paragraph" }] },
        category: "test",
        createdAt: now,
        status: "draft",
      });
    }

    // Upsert published post
    const existingPublished = await ctx.db
      .query("posts")
      .withIndex("by_userId_and_slug", (q) =>
        q.eq("userId", userId).eq("slug", PUBLISHED_FIXTURE_SLUG),
      )
      .unique();

    if (existingPublished) {
      await ctx.db.patch(existingPublished._id, {
        status: "published",
        title: "Test Published Post",
        publishedAt: existingPublished.publishedAt ?? now,
        body: existingPublished.body ?? { type: "doc", content: [{ type: "paragraph" }] },
      });
    } else {
      await ctx.db.insert("posts", {
        userId,
        slug: PUBLISHED_FIXTURE_SLUG,
        title: "Test Published Post",
        body: { type: "doc", content: [{ type: "paragraph" }] },
        category: "test",
        createdAt: now,
        publishedAt: now,
        status: "published",
      });
    }

    return {
      draftSlug: DRAFT_FIXTURE_SLUG,
      publishedSlug: PUBLISHED_FIXTURE_SLUG,
    };
  },
});

/**
 * Deletes testOtpStore rows older than TEST_OTP_TTL_MS. Scheduled from crons.ts
 * to keep the table from accumulating stale rows in dev/test environments.
 */
const TEST_OTP_TTL_MS = 10 * 60 * 1000; // 10 minutes

export const cleanupStaleTestOtps = internalMutation({
  args: {},
  returns: v.null(),
  handler: async (ctx) => {
    const cutoff = Date.now() - TEST_OTP_TTL_MS;
    const stale = await ctx.db
      .query("testOtpStore")
      .withIndex("by_createdAt", (q) => q.lt("createdAt", cutoff))
      .collect();
    for (const row of stale) {
      await ctx.db.delete(row._id);
    }
    return null;
  },
});
